### ISSUE TITLE
CGX swep 

### ISSUE THREAD

**Issue by 3rav** [mkraska/CalculiX-Examples#24]
Swep command badly (wrong) creates surfaces by rotation (swep set set rot y 90 a):
- ellipse (example)
- part of the circle is also badly formed!

![aa](https://user-images.githubusercontent.com/24394573/31014152-c9352a52-a519-11e7-92d9-0d3a7b734c5f.png)

**Comment by mkraska** [comment]
This problem has been resolved by introduction of the parameter "n" in CGX 2.12.
Example: Compare the hemispheric indenter:
CGX 2.11:  https://github.com/mkraska/CalculiX-Examples/tree/v2.11/Contact/Shell1
CGX 2.12:  https://github.com/mkraska/CalculiX-Examples/tree/v2.12/Contact/Shell1
