### ISSUE TITLE
CGX out-of-range (above range color) enhancement

### ISSUE THREAD

**Issue by 3rav** [mkraska/CalculiX-Examples#25]
Add features "use above range color" like in paraview.

max 0.002 g
g - gray

![abowe range](https://user-images.githubusercontent.com/24394573/31014645-420fff72-a51c-11e7-96ea-d3ed4649db9e.png)

![outofrangecolors](https://user-images.githubusercontent.com/24394573/31014646-421104d0-a51c-11e7-94fb-3796214cdc0a.png)

**Comment by mkraska** [comment]
In CGX 2.13 there will be the commands maxr and minr. These, however, won't allow to select the color of the above or below range, they merely shift the specified min/max values from the end of the colorbar to the adjacent color step.

**Comment by 3rav** [comment]
Thank you for your answer.
When can we expect (more or less) release of version 2.13?

Regards
Rafal

**Comment by mkraska** [comment]
cgx 2.13 is published.
