### ISSUE TITLE
Extended valu command

### ISSUE THREAD

**Issue by 3rav** [mkraska/CalculiX-Examples#26]
Hi,

Please consider adding:
The possibility of easy manipulation (performing calculations) on datasets from the .frd file would be very helpful in calculations by ASME.
Now to perform calculations "Determine the limiting Triaxial strain" I use Praview (ccx + exodus extras):
![kd-232 2](https://user-images.githubusercontent.com/24394573/34094329-0cd6dffc-e3cd-11e7-9e14-526bbe319706.png)
 
I know I can use userFunction.c but it is quite difficult for a non-programmer.

Example:
read all.frd
valu e1 2.7182
valu m2 0.2743
valu m5 0.3657
valu elu 0.2743

valu A1a + PS1 PS2
valu A1b + A1a PS3
valu A2 * 3 Mises

valu B1 / A1b A2
valu B2 - B1 0.33

and so on, and the results could be displayed in the form of a map.

Regards
Rafal

**Comment by mkraska** [comment]
I agree that this would be useful.

**Comment by mkraska** [comment]
Should be possible in CGX 2.15
