### ISSUE TITLE
CGX valu

### ISSUE THREAD

**Issue by 3rav** [mkraska/CalculiX-Examples#27]
Hi,
I would like to propose an extension of the valu command, adding the ability to retrieve the coordinate value of a specific point.

For instance:

In file part1.fbd a have point p1 (pnt p1 10. 32. 0.45673), I read this file to assemble.fbd and in this file I want to create new point with the "z" value of p1.

read part1.fbd
valu namex x p1 
valu namey y p1
valu namez z p1
pnt p2 45. 0.  namez

Regards
Rafal

**Comment by mkraska** [comment]
prnt p <pointname>
displays the co-ordinates of the point and writes them to the stack if switched on. 
Then you can pop the value from the stack.

**Comment by 3rav** [comment]
Thank you very much for this information
