### ISSUE TITLE
Library not loaded

### ISSUE THREAD

**Issue by sayluv** [mkraska/CalculiX-Examples#32]
Hi-
I apologize if this isn't the proper place to ask. I am trying to run Calculix from a command line but I am having some install issues. I know very little about this stuff so I apologize.

I installed Calculix with these commands:

brew tap brewsci/science
brew install calculix-ccx

Here is the error I am receiving and my system info: thanks.

OSX High Sierra
v 10.13.6

dyld: Library not loaded: /usr/local/opt/gcc/lib/gcc/7/libgfortran.4.dylib
  Referenced from: /usr/local/bin/ccx_2.13
  Reason: image not found
Abort trap: 6

**Comment by mkraska** [comment]
Sorry, I have no experience with OSX. Please refer to the Calculix yahoo forum.
