### ISSUE TITLE
testall.py: close windows automatically

### ISSUE THREAD

**Issue by imirzov** [mkraska/CalculiX-Examples#36]
Hi!

Your examples are amazing! But running testall.py I must manually close GMSH and GraphiX windows for all examples. Please, could you implement automatic close of all windows?

**Comment by imirzov** [comment]
Here is solution:
https://github.com/mkraska/CalculiX-Examples/pull/38

**Comment by mkraska** [comment]
Thanks a lot for the contribution. I'd like to keep the option to interactively explore the examples in CGX. In this case it is desirable that the CGX windows stay open. 
Possibly, we could use a special init script for CGX if automatic closing of the window is required.
I shall ask Klaus Wittig for a recommendation.

**Comment by mkraska** [comment]
The recommendation by Klaus is to put a read command to the end of the script. The file to be read contains the quit command when in batch mode and nothing if in interactive mode.

The disadvantage is that you have to take care of this in every new fbd script. Therefore, I prefer to temporarily append a line to the script. Perhaps a standard test procedure might look like this:
- copy all pre-requisites to a test folder
- make any modifications for batch mode (quit/exit commands)
- run the example
- run comparison
- write test log

**Comment by imirzov** [comment]
Here is first try to implement my idea:
https://github.com/mkraska/CalculiX-Examples/pull/45
