### ISSUE TITLE
CalculiX model files extensions

### ISSUE THREAD

**Issue by imirzov** [mkraska/CalculiX-Examples#42]
Dear Prof. Kraska,

In your wonderful Examples you use too wide variety of file extensions for the same file type - INP.
Files with extensions msh, nam, dlo, sur, con, bou, inc, equ, frc, dfl are of the same type and could have the same extension - INP extension.

**Comment by mkraska** [comment]
This is a design decision made by Klaus Wittig. The files mentioned are generated by CGX with automatic file names based on the command parameters. One might ask Klaus to add an option to append .inp to whatever input snippet is generated for ccx, but I wouldn't really vote for it, as I don't see substantial benefit.

It would be possible to issue renaming commands after each write operation from CGX. However, this would bloat the scripts and reduce the signal to noise ratio (readability).

I think it is quite sensible to restrict the INP extension to files executable by ccx, i.e. top level input files. If you aim at syntax highlighting support in editors, then it should be possible to register additional extensions for abaqus/ccx mode.
