### ISSUE TITLE
Discord channel for Calculix

### ISSUE THREAD

**Issue by Foadsf** [mkraska/CalculiX-Examples#48]
Hi @mkraska ,

I have recently created a Discord channel for Calculix on Elmer's Discord:

 https://discord.gg/yyuQQg5

looking forward to having the rest of the community over there as well.

**Comment by mkraska** [comment]
There doesn't seem to be any traffic in the last weeks...

**Comment by Foadsf** [comment]
@mkraska that channel is relatively new. The more people coming to the server, the more people we attract. So try to stay there by installing the Discord app on your phone or computer. and if you know other CalculiX people please invite them.

**Comment by benzwick** [comment]
There is now also the CalculiX discourse page: https://calculix.discourse.group

**Comment by mkraska** [comment]
The discourse group seems to be accepted by the community, therefore I close this issue.
