### ISSUE TITLE
Displacement as a load 

### ISSUE THREAD

**Issue by Murtaza-hash** [mkraska/CalculiX-Examples#53]
Hi everyone,
I want to bring a load as a displacement, but I dont know how. Could you help me please?

**Comment by oldninja** [comment]
Hi @Murtaza-hash, you could use the boundary card:
`*BOUNDARY`
`2,1,,0.1`
Here I applied a 0.1 displacement at node 2 in the 1st direction.
Good luck!

**Comment by Murtaza-hash** [comment]
Hi oldninja,
Thank you very very very x 1000 much. It has helped me. I searched that for days.
