### ISSUE TITLE
Import SETs into assembly (referring to the Contact tutorial)

### ISSUE THREAD

**Issue by Nobody-86** [mkraska/CalculiX-Examples#56]
Hi mkraska,

I have seen your example of assembling (Contact), I have a further question: Is it somehow possible to import SETs?

For this the following example:
I have a Mesh in FRD format and the sets as NAM file. The structure of the files is (as an example)

part.frd:
----------
1CMESH
1UTest
2C 12345 1
-1 1 0.00000E+03 0.00000E+03 0.00000E+03
-1 2 1.00000E+03 0.00000E+03 0.00000E+03
[...]

part.nam:
----------
seta N_LEFT n 1
seta N_LEFT n 2
seta N_RIGHT n 3
[...]

If I now import both twice with

seto part_one
read part.frd
read part.nam
setc
seto part_two
read part.frd
read part.nam
setc

the second part did not get the correct nodes from the NAM file (which is somehow obvious, since the node numbers in the FRD are incremented, but those in the NAM file are not).

Is it somehow possible to load multiple parts into one assembly and keep the SETs?

PS: I am completely free in the way the files have to be prepared, because I create the mesh with a converter I wrote myself and can adjust the output to the needs.

Thanks a lot! Also for the many great examples!

**Comment by mkraska** [comment]
I have never worked with multiple frd files in a cgx session. Perhaps better ask in the discourse forum https://calculix.discourse.group/
