### ISSUE TITLE
CGX feature request: frame <set>

### ISSUE THREAD

**Issue by mkraska** [mkraska/CalculiX-Examples#7]
Extend the command 'frame' such that it can fit the view to a given set. Possible applications:
- create images of parts 
- show all elements with values above a particular one.
  This would extract all nodes with values above 200
  enq nodes roi rec _ _ _ 1 h 200
  frame roi would then zoom into that region.

frame h 200 would be more elegant but also more special, less universal.

**Comment by mkraska** [comment]
Implemented in CGX 2.13

**Comment by 3rav** [comment]
Hi,

Set a good view of the model by commands (np. zoom, frame, tra) to make a screenshot is very difficult.

A very useful option would be to set the model view manually (by mouse) and then save that view/frame/position in to the file (eg send abq frame), then in the script file (like post.fbd) that executes a series of screenshots loading this file/position of model (eg read view.frame).

Regards
Rafal
